#!/usr/bin/env bash

# Use this one-liner to produce a JSON literal from the Git log:

git log \
    --date=iso8601-strict \
    --pretty=format:'{%n  "commit": "%H",%n  "author": "%aN <%aE>",%n  "date": "%ad",%n  "message": "%f"%n},' \
    "$@" | \
    perl -pe 'BEGIN{print "["}; END{print "]\n"}' | \
    perl -pe 's/},]/}]/' | \
    perl -pe 's{\\}{\\\\}g'
